const initialStates = {
  click: {
    Name: "",
    State: "",
    City: "",
    Neighborhood: "",
    Street: "",
    Number: "",
    Compements: "",
    Site: "",
  },
  cursinho: [
    {
      id: 1,
      Name: "Cursinho Ativo Unesp Jaboticabal",
      State: "SP",
      City: "Jaboticabal",
      Neighborhood: "Jardim Guanabara",
      Street: "R Prof Paulo Donato Castellane",
      Number: "S/N",
      Compements: "",
      Site: "https://www.facebook.com/cursinhoativojaboticabal/",
      lat: -21.2755224,
      lng: -48.3260669,
    },
    {
      id: 2,
      Name: "Colmeia",
      State: "SP",
      City: "Limeira",
      Neighborhood: "Jardim Morro Azul",
      Street: "R Francisco Bisca",
      Number: "121",
      Compements: "",
      Site:
        "https://www.fca.unicamp.br/portal/pt-br/extensao/ext-projetos/1023-cursinho-pre-vestibular-colmeia-jovens-construindo-seus-projetos-de-futuro.html",
      lat: -22.5592548,
      lng: -47.429088,
    },
    {
      id: 3,
      Name: "Cursinho Unificado do Campus de Araraquara (CUCA)",
      State: "SP",
      City: "Araraquara",
      Neighborhood: "Jardim Quitandinha",
      Street: "Av Prof Francisco Degni",
      Number: "55",
      Compements: "",
      Site: "https://www.facebook.com/cuca.iq/",
      lat: -21.8073822,
      lng: -48.1924118,
    },
    {
      id: 4,
      Name: "Cursinho Comunitário Professor Lourenço Filho",
      State: "SP",
      City: "Porto Ferreira",
      Neighborhood: "Planalto Paulista",
      Street: "Alameda dos Tacaúnas",
      Number: "181",
      Compements: "",
      Site: "https://www.facebook.com/groups/837256073041949/?ref=share",
      lat: -23.6209871,
      lng: -46.64405989999999,
    },
    {
      id: 5,
      Name: "Cursinho da Poli",
      State: "SP",
      City: "São Paulo",
      Neighborhood: "Butanta",
      Street: "Avenida Professor Almeida Prado",
      Number: "128",
      Compements: "",
      Site: "https://instagram.com/cursinhopoliusp?igshid=ijwa0ay115vc",
      lat: -23.5562257,
      lng: -46.7330966,
    },
    {
      id: 6,
      Name: "Cursinho da Psico",
      State: "SP",
      City: "São Paulo",
      Neighborhood: "Butanta",
      Street: "Av Professor Mello Moraes",
      Number: "1721",
      Compements: "Bloco B",
      Site: "https://www.facebook.com/cursinho.psico",
      lat: -23.556093,
      lng: -46.7243613,
    },
    {
      id: 7,
      Name: "Cursinho Geração Near",
      State: "SP",
      City: "Araraquara",
      Neighborhood: "Jardim do Carmo",
      Street: "R dos Libaneses",
      Number: "1111",
      Compements: "",
      Site: "https://instagram.com/geracao.near?igshid=1rtrxawmzlapv",
      lat: -21.8033678,
      lng: -48.18479,
    },
    {
      id: 8,
      Name: "Cursinho Livre Caburé",
      State: "SP",
      City: "Araraquara",
      Neighborhood: "Centro",
      Street: "Av Feijó",
      Number: "207",
      Compements: "",
      Site: "https://www.cursinhocabure.org",
      lat: -21.7921627,
      lng: -48.1814534,
    },
    {
      id: 9,
      Name: "Cursinho Popular Contexto",
      State: "SP",
      City: "Valinhos",
      Neighborhood: "Vila Clayton",
      Street: "Av Onze de Agosto",
      Number: "860",
      Compements: "",
      Site: "https://www.facebook.com/ongtempobom/",
      lat: -22.9740268,
      lng: -46.9962072,
    },
    {
      id: 10,
      Name: "Cursinho Popular da Faculdade de Direito de Ribeirão Preto",
      State: "SP",
      City: "Ribeirao Preto",
      Neighborhood: "Vila Virginia",
      Street: "Av Bandeirantes",
      Number: "3900",
      Compements: "",
      Site: "https://m.facebook.com/cursinhopopulardafdrp/",
      lat: -21.1736879,
      lng: -47.8582776,
    },
    {
      id: 11,
      Name: "Cursinho popular da medicina",
      State: "SP",
      City: "Ribeirao Preto",
      Neighborhood: "Vila Virginia",
      Street: "Av Bandeirantes",
      Number: "3900",
      Compements: "",
      Site: "http://pet-fmrp.com.br/cursinhodamedicina/",
      lat: -21.1736879,
      lng: -47.8582776,
    },
    {
      id: 12,
      Name: "Cursinho Popular de Vinhedo",
      State: "SP",
      City: "Vinhedo",
      Neighborhood: "Nova Vinhedo",
      Street: "R António Vendramini",
      Number: "31",
      Compements: "",
      Site: "https://instagram.com/cursinhovinhedo",
      lat: -23.0228132,
      lng: -46.9857515,
    },
    {
      id: 13,
      Name: "Cursinho Popular Dra Jurema Gomes Xavier",
      State: "SP",
      City: "Franca",
      Neighborhood: "Res Baldassari",
      Street: "R Comendador Nassim Melen",
      Number: "2377",
      Compements: "",
      Site: "https://www.facebook.com/cpfdf.jurema/",
      lat: -20.5361985,
      lng: -47.3905245,
    },
    {
      id: 14,
      Name: "Cursinho Popular Guimarões Rosa",
      State: "MG",
      City: "Belo Horizonte",
      Neighborhood: "Santa Efigênia",
      Street: "Av Professor Alfredo Balena",
      Number: "190",
      Compements: "",
      Site: "https://www.instagram.com/guimaraesrosacp/",
      lat: -19.9244415,
      lng: -43.9290063,
    },
    {
      id: 15,
      Name: "Cursinho Popular Sabotage",
      State: "SP",
      City: "Sumaré",
      Neighborhood: "Parque das Nações",
      Street: "R Aldo de Oliveira Miler",
      Number: "393",
      Compements: "",
      Site: "https://www.facebook.com/CPsabotage",
      lat: -22.8335651,
      lng: -47.18429039999999,
    },
    {
      id: 16,
      Name: "Cursinho Popular Zilda Arns",
      State: "SP",
      City: "Campinas",
      Neighborhood: "Barão Geraldo",
      Street: "Cidade Universitária Zeferino Vaz",
      Number: "S/N",
      Compements: "",
      Site: "https://instagram.com/cursinhozilda?igshid=u4c7ubl1xgrr",
      lat: -22.8184393,
      lng: -47.0647206,
    },
    {
      id: 17,
      Name: "Cursinho Pré-Vestibular Cuca Fresca",
      State: "SP",
      City: "Itapeva",
      Neighborhood: "Vila Nossa Senhora de Fatima",
      Street: "R Geraldo Alckmin",
      Number: "519",
      Compements: "",
      Site: "https://cursinhocucafresca.wordpress.com/",
      lat: -23.981165,
      lng: -48.883243,
    },
    {
      id: 18,
      Name: "Cursinho Pré-vestibular da Universidade Federal de São Carlos",
      State: "SP",
      City: "São Carlos",
      Neighborhood: "",
      Street: "Rod Washington Luis",
      Number: "km 235",
      Compements: "",
      Site: "https://cursinho.faiufscar.com/",
      lat: -21.9876777,
      lng: -47.8790139,
    },
    {
      id: 19,
      Name: "Cursinho solidário",
      State: "PR",
      City: "Curitiba",
      Neighborhood: "Batel",
      Street: "R Bueno Aires",
      Number: "441",
      Compements: "9 Andar, Sala 94",
      Site: "http://www.formacaosolidaria.org.br/",
      lat: -25.4414534,
      lng: -49.2791481,
    },
    {
      id: 20,
      Name: "Cursinho Vitoriano",
      State: "SP",
      City: "São José do Rio Preto",
      Neighborhood: "Eldorado",
      Street: "R Fernandópolis",
      Number: "2510",
      Compements: "",
      Site: "http://www.cursinhovitoriano.com/cv/index",
      lat: -20.7935135,
      lng: -49.3997521,
    },
    {
      id: 21,
      Name: "Cursinho Vitoriano",
      State: "SP",
      City: "São José do Rio Preto",
      Neighborhood: "Jardim Nazareth",
      Street: "R Cristóvão Colombo",
      Number: "2265",
      Compements: "",
      Site: "http://www.cursinhovitoriano.com/cv/index",
      lat: -20.7867532,
      lng: -49.3602077,
    },
    {
      id: 22,
      Name: "Emancipa VPA",
      State: "SP",
      City: "Campinas",
      Neighborhood: "Jardim Aparecida",
      Street: "R Adão Gonçalves",
      Number: "S/N",
      Compements: "",
      Site: "https://inscricoes.redeemancipa.org.br/pt/sp/padre-anchieta",
      lat: -22.850222,
      lng: -47.1465782,
    },
    {
      id: 23,
      Name: "ONG Cursinho Professor Chico Poço",
      State: "SP",
      City: "Jundiai",
      Neighborhood: "Vila Mafalda",
      Street: "R. Elías Fausto",
      Number: "27",
      Compements: "",
      Site: "https://www.cursinhocp2.org/",
      lat: -23.2125533,
      lng: -46.8734563,
    },
    {
      id: 24,
      Name: "Podemos São Carlos",
      State: "SP",
      City: "São Carlos",
      Neighborhood: "",
      Street: "R Alberto Lanzoni",
      Number: "1381",
      Compements: "",
      Site: "https://www.facebook.com/2073903909390563/posts/3089780134469597/",
      lat: -22.0090851,
      lng: -47.9184043,
    },
    {
      id: 25,
      Name: "TRIU",
      State: "SP",
      City: "Campinas",
      Neighborhood: "Barão Geraldo",
      Street: "R Jerônimo Pattaro",
      Number: "S/N",
      Compements: "",
      Site: "http://www.cursinhotriu.com.br/",
      lat: -22.8816884,
      lng: -47.0437063,
    },
    {
      id: 26,
      Name: "Zilda Arns",
      State: "SP",
      City: "Campinas",
      Neighborhood: "Cidade Universitária",
      Street: "R. Tessália Vieira de Camargo",
      Number: "126",
      Compements: "",
      Site: "https://www.cursinhozilda.com/",
      lat: -22.8313634,
      lng: -47.062304,
    },
  ],
};

export default initialStates;
